### ISSUE TITLE
Code and resource path updates

### ISSUE THREAD

**Issue by hpreston** [networktocode/ntc-misc#2]
I was taking another look and noticed the path for the code samples wasn't updated to match the move from `sbx_nxos/yang` -> `sbx_nxos/learning_labs/yang` in the instructions.  This will need to be fixed across all three labs.  

@termlen0

**Comment by termlen0** [comment]
The updates were in a branch. I have now merged it into master. 
-ajay

**Comment by termlen0** [comment]
Please verify and close if fixed.

**Comment by hpreston** [comment]
I just checked the yang labs (at least the first one) and it still has in the markdown file the old path references.  

https://github.com/networktocode/ntc-misc/blob/master/cisco/yang/nxos-nc-yang-m1.md

**Comment by termlen0** [comment]
I've addressed this via PR #6 . Please review and close.

**Comment by hpreston** [comment]
Looks good.  Thanks.
